# Generated by Django 4.1.3 on 2023-03-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='body',
        ),
        migrations.AddField(
            model_name='like',
            name='Likes',
            field=models.IntegerField(default=True),
        ),
    ]
